### ISSUE TITLE
Создать actor.php

### ISSUE THREAD

**Issue by berrykot** [berrykot/commonBatmanProject#1]
Подгружать данные об актёре на страницу actor.php?id=$_GET["Id"]

Для выполнения концепции, проще всего будет воспользоваться php include() файла commonBatmanProject\htmlTemplates\body.php из связанной задачи (related issue) #11 

[Концепция страницы](https://github.com/berrykot/commonBatmanProject/wiki/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0%D1%8F-%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%86%D0%B8%D1%8F-%D1%81%D0%B0%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86)

**Comment by berrykot** [comment]
Костян я не буду ее делать

**Comment by berrykot** [comment]
@vladteen , файл переехал в папку commonBatmanProject\pages

**Comment by vladteen** [comment]
Выполнено!
